title: Andy Thomas
logo: "/images/me75.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/andycthomas/">View My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
